theme: jekyll-theme-minimal
show_downloads: true
logo: ![image](https://user-images.githubusercontent.com/80940234/111784229-2b46a000-88e1-11eb-92f9-cccefef79d92.png)

social-network-links:
  email: "k.arpan@outlook.com"
  github: iArpanK
  twitter: iArpanK
